# Is a sample different? {}
One of the most common questions in statistics is to ask if the average from a given sample is different from what will be expected in a population. We did one of such test with a simulation at the end of last chapter. Here we will run a more practical approach to answer the question if a sample is different from a population.

**Expectation for this chapter**

At the end of this chapter, it is expected that you you can test a null hypothesis using the Z-score.

## The Z-score {-}
As it has been indicated several times in this book, it is relatively easy to know the proportion of individuals in a population at certain standard deviations from the mean. AS an example, plus or minus two standard deviations from the mean include about 95% of the individuals in that population (assuming of course the population is normally distributed). Given this principle then you can easily know the fraction or individuals  

## Exercises {-}
Some of these questions may take a while to load depending on your internet connection.




## Homework {-}
