<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Descriptive statistics | GEOG380.utf8</title>
  <meta name="description" content="This is a entry level course to learn stats and R" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Descriptive statistics | GEOG380.utf8" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a entry level course to learn stats and R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Descriptive statistics | GEOG380.utf8" />
  
  <meta name="twitter:description" content="This is a entry level course to learn stats and R" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="04-RBasics-Plots.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a>GEOG380 Basic Stats with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#introduction"><i class="fa fa-check"></i>Introduction</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#book-data-collection"><i class="fa fa-check"></i>Book data collection</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#what-is-r"><i class="fa fa-check"></i>What is R?</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#do-not-dispair-please"><i class="fa fa-check"></i>Do not dispair, please</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html"><i class="fa fa-check"></i><b>1</b> The scientific method</a><ul>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#the-problem"><i class="fa fa-check"></i>The problem</a><ul>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#narrow-the-problem"><i class="fa fa-check"></i>Narrow the problem</a></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#search-prior-knowledge"><i class="fa fa-check"></i>Search prior knowledge</a></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#back-to-defining-the-problem"><i class="fa fa-check"></i>Back to defining the problem</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#the-hyphotesis"><i class="fa fa-check"></i>The hyphotesis</a><ul>
<li><a href="01-ScientificMethod.html#the-null-hypothesis-h0">The null hypothesis <em>H0</em></a></li>
<li><a href="01-ScientificMethod.html#the-alternate-hypothesis-h1">The alternate hypothesis <em>H1</em></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#the-experiment"><i class="fa fa-check"></i>The experiment</a><ul>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#population-sample-subject"><i class="fa fa-check"></i>Population, sample, subject</a></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#variables"><i class="fa fa-check"></i>Variables</a></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#the-control-and-treatment"><i class="fa fa-check"></i>The control and treatment</a></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#replication"><i class="fa fa-check"></i>Replication</a></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#pseudo-replication"><i class="fa fa-check"></i>Pseudo-Replication</a></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#randomness"><i class="fa fa-check"></i>Randomness</a></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#design-experiment"><i class="fa fa-check"></i>Design experiment</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#data-collection"><i class="fa fa-check"></i>Data collection</a></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#analyze-your-data"><i class="fa fa-check"></i>Analyze your data</a></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#vizualize-the-data"><i class="fa fa-check"></i>Vizualize the data</a></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#write-report"><i class="fa fa-check"></i>Write report</a></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#excercises"><i class="fa fa-check"></i>Excercises</a><ul>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#exercise-1"><i class="fa fa-check"></i>Exercise 1</a></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#exercise-2"><i class="fa fa-check"></i>Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="01-ScientificMethod.html"><a href="01-ScientificMethod.html#homework"><i class="fa fa-check"></i>Homework</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="02-00-InstallingR.html"><a href="02-00-InstallingR.html"><i class="fa fa-check"></i><b>2</b> Installing programs</a><ul>
<li class="chapter" data-level="" data-path="02-00-InstallingR.html"><a href="02-00-InstallingR.html#installing-r"><i class="fa fa-check"></i>Installing R</a></li>
<li class="chapter" data-level="" data-path="02-00-InstallingR.html"><a href="02-00-InstallingR.html#tinn-r"><i class="fa fa-check"></i>Tinn-R</a></li>
<li class="chapter" data-level="" data-path="02-00-InstallingR.html"><a href="02-00-InstallingR.html#r-studio"><i class="fa fa-check"></i>R-Studio</a></li>
<li class="chapter" data-level="" data-path="02-00-InstallingR.html"><a href="02-00-InstallingR.html#installing-packages"><i class="fa fa-check"></i>Installing packages</a></li>
<li class="chapter" data-level="" data-path="02-00-InstallingR.html"><a href="02-00-InstallingR.html#asking-for-help"><i class="fa fa-check"></i>Asking for help</a></li>
<li class="chapter" data-level="" data-path="02-00-InstallingR.html"><a href="02-00-InstallingR.html#exercise"><i class="fa fa-check"></i>Exercise</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html"><i class="fa fa-check"></i><b>3</b> Basics on data manipulation in R</a><ul>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#variables-1"><i class="fa fa-check"></i>Variables</a></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#comments"><i class="fa fa-check"></i>Comments</a></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#operators"><i class="fa fa-check"></i>Operators</a><ul>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#assignment-operators"><i class="fa fa-check"></i>Assignment operators</a></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#arithmetic-operators"><i class="fa fa-check"></i>Arithmetic operators</a></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#character-operators"><i class="fa fa-check"></i>Character operators</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#custom-made-functions"><i class="fa fa-check"></i>Custom made functions</a></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#data-structure-types"><i class="fa fa-check"></i>Data structure types</a><ul>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#vectors"><i class="fa fa-check"></i>Vectors</a></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#matrix"><i class="fa fa-check"></i>Matrix</a></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#dataframes"><i class="fa fa-check"></i>DataFrames</a></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#loading-your-own-data-into-r"><i class="fa fa-check"></i>Loading your own data into R</a></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#calling-elements"><i class="fa fa-check"></i>Calling elements</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#filter-data"><i class="fa fa-check"></i>Filter data</a></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#pivot-table"><i class="fa fa-check"></i>Pivot table</a></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#merge-data"><i class="fa fa-check"></i>Merge data</a></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#subsetting-columns"><i class="fa fa-check"></i>Subsetting columns</a><ul>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#deleting-columns"><i class="fa fa-check"></i>Deleting columns</a></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#selecting-columns"><i class="fa fa-check"></i>Selecting columns</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#adding-results-to-databases"><i class="fa fa-check"></i>Adding results to databases</a></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#exercise-3"><i class="fa fa-check"></i>Exercise</a></li>
<li class="chapter" data-level="" data-path="03-RBasics-DataManipulation.html"><a href="03-RBasics-DataManipulation.html#homework-1"><i class="fa fa-check"></i>Homework</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="04-RBasics-Plots.html"><a href="04-RBasics-Plots.html"><i class="fa fa-check"></i><b>4</b> Basic plots</a><ul>
<li class="chapter" data-level="" data-path="04-RBasics-Plots.html"><a href="04-RBasics-Plots.html#scatterplots"><i class="fa fa-check"></i>Scatterplots</a></li>
<li class="chapter" data-level="" data-path="04-RBasics-Plots.html"><a href="04-RBasics-Plots.html#histograms"><i class="fa fa-check"></i>Histograms</a></li>
<li class="chapter" data-level="" data-path="04-RBasics-Plots.html"><a href="04-RBasics-Plots.html#density-plots"><i class="fa fa-check"></i>Density plots</a></li>
<li class="chapter" data-level="" data-path="04-RBasics-Plots.html"><a href="04-RBasics-Plots.html#plotting-maps"><i class="fa fa-check"></i>Plotting maps</a></li>
<li class="chapter" data-level="" data-path="04-RBasics-Plots.html"><a href="04-RBasics-Plots.html#animated-plots"><i class="fa fa-check"></i>Animated plots</a></li>
<li class="chapter" data-level="" data-path="04-RBasics-Plots.html"><a href="04-RBasics-Plots.html#saving-plots"><i class="fa fa-check"></i>Saving plots</a></li>
<li class="chapter" data-level="" data-path="04-RBasics-Plots.html"><a href="04-RBasics-Plots.html#excersise"><i class="fa fa-check"></i>Excersise</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html"><i class="fa fa-check"></i><b>5</b> Descriptive statistics</a><ul>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#data-distributions"><i class="fa fa-check"></i>Data distributions</a></li>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#central-tendency"><i class="fa fa-check"></i>Central tendency</a><ul>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#the-arithmetic-mean"><i class="fa fa-check"></i>The arithmetic mean</a></li>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#the-trimmed-mean"><i class="fa fa-check"></i>The trimmed mean</a></li>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#the-weighted-average"><i class="fa fa-check"></i>The weighted average</a></li>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#the-median"><i class="fa fa-check"></i>The median</a></li>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#the-mode"><i class="fa fa-check"></i>The mode</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#dispersion"><i class="fa fa-check"></i>Dispersion</a><ul>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#the-minimum-and-the-maximum"><i class="fa fa-check"></i>The minimum and the maximum</a></li>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#the-range"><i class="fa fa-check"></i>The range</a></li>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#the-percentile"><i class="fa fa-check"></i>The percentile</a></li>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#the-quantile"><i class="fa fa-check"></i>The quantile</a></li>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#the-variance"><i class="fa fa-check"></i>The variance</a></li>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#the-standard-deviation"><i class="fa fa-check"></i>The standard deviation</a></li>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#the-coefience-of-variance"><i class="fa fa-check"></i>The coefience of variance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#exercises"><i class="fa fa-check"></i>Exercises</a></li>
<li class="chapter" data-level="" data-path="05-DescriptiveStatistics.html"><a href="05-DescriptiveStatistics.html#homework-2"><i class="fa fa-check"></i>Homework</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="http://www.soc.hawaii.edu/mora/index.html"><img src="images/MoraLab.png" width="270"></a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><h1 style="font-size:17px">
By Camilo Mora, Ph.D.
</h1></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="descriptive-statistics" class="section level1">
<h1><span class="header-section-number">5</span> Descriptive statistics</h1>
<iframe width="560" height="315" src="https://www.youtube.com/embed/OLCReYns0dQ" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
<p>Ok, guys, by now you know how:</p>
<ol style="list-style-type: decimal">
<li>to set a question,</li>
<li>reformulate the question based on your literature review,</li>
<li>set up an error proof experiment,</li>
<li>enter and manipulate data in R and</li>
<li>do some basic plots in R.</li>
</ol>
<p>Nice, ah?.</p>
<p>Now we move on to the analysis of any data you collect. That process is called <strong>inference</strong>; basically, drowning a conclusion based on the numbers and your interpretation of those numbers.</p>
<p>iii</p>

<div class="rmdnote">
Inference is defined as the process of drawing conclusions based on evidence and reasoning.
</div>

<p>Once you finish an experiment and collect your data, there are a few things to do:</p>
<p>First, you need visualize the data, using plots you learned how to do in the prior chapter.</p>
<p>Second, you need to use a set of available metrics to describe your data in general. You need to get the big picture first. Those BIG picture metrics are called <strong>DESCRIPTIVE STATISTICS</strong>.</p>
<p>Say you get hired to analyze the visiting times of costumers in a store. The manager wants to ensure his costumers are always being attended to so he wants to hire more people at pick hours.</p>
<p>To tackled this problem, you probably want to record the time people walk into the store. Let’s say 100 people came in a day.</p>
<p>If you want to report your findings to the manager, you cannot just go and tell him, the first costumer came at 7 am, the second at 7:10, the third at 8:20 am….(one hour later)…and the 100th costumer came in at 7:00pm.</p>
<p>Very likely there is a pattern in that data, but the manager cannot really perceived it when the data are presented in raw form. So the manager cannot really make any decision to solve his problem based on what you did, so he may not have a reason to keep you.</p>
<p>Really what you want to do is to describe that data for him, as to facilitate his decision.</p>
<p>The metrics used to describe data overall are called <strong>descriptive statistics</strong>. Such metrics are commonly divided into those dealing with what is at the middle of your data (the so-call metrics of <strong>central tendency</strong>) and those dealing with how variable your data are (the so-call <strong>metrics of dispersion</strong>).</p>
<div id="data-distributions" class="section level2 unnumbered">
<h2>Data distributions</h2>
<p>As mentioned several times in this class, the first thing to always do when analyzing data is to create a visual representation. You need to see what are the general tendencies in your data, and for that we commonly start with the frequency distribution.</p>
<p>Lets image that the plot below is the number of seedlings (points) at each height in my nursery. Interesting, ahh?. That type of distribution is called bimodal (there are two peaks in the data). Clearly, there is something going on in my nursery, some seedlings are doing particularly better than others.</p>
<p><img src="GEOG380_files/figure-html/unnamed-chunk-143-1.png" width="672" /></p>
<p>p</p>
<p>The distribution below is called a <strong>uniform distribution</strong>, any number is just as likely.</p>
<p><img src="GEOG380_files/figure-html/unnamed-chunk-144-1.png" width="672" /></p>
<iframe src="https://www.impactsofclimatechange.info/H5P/wp-admin/admin-ajax.php?action=h5p_embed&amp;id=9" width="958" height="311" frameborder="0" allowfullscreen="allowfullscreen">
</iframe>
<script src="https://www.impactsofclimatechange.info/H5P/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>
<p>o</p>
<p>The distribution below is called a left distribution. I know, it is weird how the data tend towards the right but it is called a left distribution. It is also called negative or asymmetrical distribution. Because it has only one peak, it can also be call unimodal distribution.
<img src="GEOG380_files/figure-html/unnamed-chunk-145-1.png" width="672" /></p>
<p>In the figure below, you can explore different distributions,</p>
<iframe src="https://mora.shinyapps.io/Distributions/" width="100%" height="600px">
</iframe>
</div>
<div id="central-tendency" class="section level2 unnumbered">
<h2>Central tendency</h2>
<p>Central tendency refers to metrics that attempt to describe what is in the middle of your data. The main metrics of central tendency are the mean (also called average), the median, and the mode.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-146"></span>
<img src="images/Central%20Tendency%20Measures.png" alt="Measures of central tendency" width="100%" />
<p class="caption">
Figure 5.1: Measures of central tendency
</p>
</div>
<p>l</p>
<p>Let’s create some dummy data to see what these metrics are intended to show, how to interpret them and when to use them.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="05-DescriptiveStatistics.html#cb136-1"></a><span class="kw">set.seed</span> (<span class="dv">10</span>)</span>
<span id="cb136-2"><a href="05-DescriptiveStatistics.html#cb136-2"></a>y &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">1000</span>) <span class="co"># the function rnorm allows you to create a random set of numbers from a normal distribution</span></span>
<span id="cb136-3"><a href="05-DescriptiveStatistics.html#cb136-3"></a></span>
<span id="cb136-4"><a href="05-DescriptiveStatistics.html#cb136-4"></a><span class="co">#lets now plot that data using the hist function, you already know how to use:</span></span>
<span id="cb136-5"><a href="05-DescriptiveStatistics.html#cb136-5"></a><span class="kw">hist</span>(y, <span class="dt">main =</span> <span class="st">&quot;Normal Distribution&quot;</span>,<span class="dt">breaks =</span> <span class="dv">30</span>)</span></code></pre></div>
<p><img src="GEOG380_files/figure-html/unnamed-chunk-147-1.png" width="672" /></p>
<div id="the-arithmetic-mean" class="section level3 unnumbered">
<h3>The arithmetic mean</h3>
<p>The arithmetic mean is the average of the numbers. It is easy to calculate: add up all the numbers, then divide by how many numbers there are.</p>
<p>Mathematically, it is expressed as:</p>
<p><span class="math display">\[\begin{equation}
\bar{X} = \frac{\sum_{i=1}^n X_i}{n}
\end{equation}\]</span></p>

<div class="rmdimportant">
<p>The mean of a sample is denoted wit the letter <span class="math inline">\(\bar{X}\)</span>; at times it does not include the horizontal bar above the letter.</p>
The mean of a population is at times denoted with the lowercase letter <span class="math inline">\(u\)</span>, at times it is not cursive. They are both calculated the same way.
</div>

<p>The symbol that looks like a pacman, <span class="math inline">\(\sum_{}\)</span>, is call <strong>summation</strong>. The lower letter <span class="math inline">\(i\)</span> indicates that the summation starts from the first number (i.e., i=1), and the higher letter <em>n</em>, means the last number. <span class="math inline">\(Xi\)</span> means each value. In short, the numerator of the equation above says: sum all values starting from the first one until the last one. <span class="math inline">\(n\)</span> indicates the sample size or total number of values in your database (if it is was the average of a population, you will likely see capital letter <span class="math inline">\(N\)</span> instead of the lowercase <span class="math inline">\(n\)</span> ).</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-149"></span>
<img src="images/Stupid%20mean.jpg" alt="The stupid mean" width="100%" />
<p class="caption">
Figure 5.2: The stupid mean
</p>
</div>
<p>y</p>
<p>In R, the mean is calculated with the function mean.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="05-DescriptiveStatistics.html#cb137-1"></a>MEAN=<span class="kw">mean</span> (y, <span class="dt">na.rm =</span> <span class="ot">FALSE</span>)  <span class="co">#here I calculate the mean, and assign it to a variable.</span></span>
<span id="cb137-2"><a href="05-DescriptiveStatistics.html#cb137-2"></a>MEAN           <span class="co">#to display the variable, simply type it, and click enter</span></span></code></pre></div>
<pre><code>## [1] 0.01137474</code></pre>
<p>You may have noted that I added ‘na.rm = TRUE’ in the mean function. This command is used as a caution to calculate the mean even if you have empty values. Lets check,</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="05-DescriptiveStatistics.html#cb139-1"></a>VectorMissingAValue &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">12</span>,<span class="dv">7</span>,<span class="dv">3</span>,<span class="fl">4.2</span>,<span class="dv">18</span>,<span class="dv">2</span>,<span class="dv">54</span>,<span class="op">-</span><span class="dv">21</span>,<span class="dv">8</span>,<span class="op">-</span><span class="dv">5</span>,<span class="ot">NA</span>)<span class="co">#here I created a vector of values, incluidng a missing value NA (NA in R stands for Not Available)</span></span>
<span id="cb139-2"><a href="05-DescriptiveStatistics.html#cb139-2"></a><span class="kw">mean</span> (VectorMissingAValue)  <span class="co">#If I calculate the mean of a vector with missing values I get</span></span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>Now, if you include the command ‘na.rm = TRUE’, that will re-do the calculation excluding any missing value.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="05-DescriptiveStatistics.html#cb141-1"></a><span class="kw">mean</span> (VectorMissingAValue,<span class="dt">na.rm =</span> <span class="ot">TRUE</span>)  </span></code></pre></div>
<pre><code>## [1] 8.22</code></pre>

<div class="rmdcaution">
In most R functions, it is important to include the command ‘na.rm = TRUE’, which means to exclude any missing value. If for any reason your data has empty cells or missing values, falling to include the ‘na.rm = TRUE’ command will result in an error….again this will be a problem only when you are missing data.
</div>

<p>Alright, lets keep going. You can visualize the mean in the histogram using the function <em>abline</em>, and put a name using the <em>text</em> function, like this:</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="05-DescriptiveStatistics.html#cb143-1"></a><span class="kw">hist</span>(y, <span class="dt">main =</span> <span class="ot">NULL</span>,<span class="dt">breaks =</span> <span class="dv">30</span>, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">100</span>),)</span>
<span id="cb143-2"><a href="05-DescriptiveStatistics.html#cb143-2"></a><span class="kw">abline</span>(<span class="dt">v=</span>MEAN, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="dv">5</span>) <span class="co">#abline put a line in a figure...you use v for vertical and h for horizontal, the value that proceeds is where the line will be drawn.</span></span>
<span id="cb143-3"><a href="05-DescriptiveStatistics.html#cb143-3"></a></span>
<span id="cb143-4"><a href="05-DescriptiveStatistics.html#cb143-4"></a></span>
<span id="cb143-5"><a href="05-DescriptiveStatistics.html#cb143-5"></a><span class="kw">text</span>(<span class="st">&quot;Mean&quot;</span>,<span class="dt">x=</span>MEAN,<span class="dt">y=</span><span class="dv">100</span>, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>) <span class="co">#the text function places a label on your figure at the given x and y position you like...there are several other parameters you can control. You can also use the function *legend*, which allows you more controls, including background colors.</span></span></code></pre></div>
<p><img src="GEOG380_files/figure-html/unnamed-chunk-154-1.png" width="672" /></p>
</div>
<div id="the-trimmed-mean" class="section level3 unnumbered">
<h3>The trimmed mean</h3>
<p>There are several variations to calculate the mean, for instance the trimmed mean. One of the problems with the arithmetic mean is that it can be strongly impacted by extreme values. In those cases, it is recommend to trim the extremes and calculate the mean on the resulting values.</p>
<p>Commonly, a %5 trimmed mean should satisfy. As its name indicates, you remove the top and bottom 5% of the data, and calculate the mean on those values.</p>
<p>Lets try a simple example. Say you measured the time it took 20 students to run 100m.</p>
<p>The individual values in seconds were 10, 20, 23, 23, 22, 20, 25, 22, 20, 25, 22, 20, 25, 20, 21, 21, 23, 21, 24, and 120.</p>
<p>To calculate this in R, I put all values in a vector and calculate the mean,</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="05-DescriptiveStatistics.html#cb144-1"></a>vals=<span class="kw">c</span>(<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">23</span>,<span class="dv">23</span>,<span class="dv">22</span>,<span class="dv">20</span>,<span class="dv">25</span>,<span class="dv">22</span>,<span class="dv">20</span>,<span class="dv">25</span>,<span class="dv">22</span>,<span class="dv">20</span>,<span class="dv">25</span>,<span class="dv">20</span>,<span class="dv">21</span>,<span class="dv">21</span>,<span class="dv">23</span>,<span class="dv">21</span>,<span class="dv">24</span>,<span class="dv">120</span>)</span>
<span id="cb144-2"><a href="05-DescriptiveStatistics.html#cb144-2"></a>  </span>
<span id="cb144-3"><a href="05-DescriptiveStatistics.html#cb144-3"></a>  <span class="kw">mean</span>(vals)</span></code></pre></div>
<pre><code>## [1] 26.35</code></pre>
<p>But from the data, you can tell that one student was very fast (only took 10 secs) and another one was very slow (he took 120secs). Lets try a 5% trimmed mean,</p>
<p>First, you sort the data from smallest to largest,</p>
<p><span style="color: red;">10</span>,20,20,20,20,20,21,21,21,22,22,22,23,23,23,24,25,25,25,<span style="color: red;">120</span></p>
<p>Now you remove the first and last (i.e, 5% of 20 is 1, so you delete the bottom and top one records, red numbers in the array).</p>
<p>Now calculate the mean of the resulting data or the so-call 5% trimmed mean:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="05-DescriptiveStatistics.html#cb146-1"></a>Trimmedvals=<span class="kw">c</span>(<span class="dv">20</span>,<span class="dv">23</span>,<span class="dv">23</span>,<span class="dv">22</span>,<span class="dv">20</span>,<span class="dv">25</span>,<span class="dv">22</span>,<span class="dv">20</span>,<span class="dv">25</span>,<span class="dv">22</span>,<span class="dv">20</span>,<span class="dv">25</span>,<span class="dv">20</span>,<span class="dv">21</span>,<span class="dv">21</span>,<span class="dv">23</span>,<span class="dv">21</span>,<span class="dv">24</span>)</span>
<span id="cb146-2"><a href="05-DescriptiveStatistics.html#cb146-2"></a>  </span>
<span id="cb146-3"><a href="05-DescriptiveStatistics.html#cb146-3"></a><span class="kw">mean</span>(Trimmedvals)</span></code></pre></div>
<pre><code>## [1] 22.05556</code></pre>
<p>The 5% trimmed mean is 22.06 compared to the arithmetic mean 26.35.</p>
</div>
<div id="the-weighted-average" class="section level3 unnumbered">
<h3>The weighted average</h3>
<p>Sometimes we wish to average numbers, but we want to assign more importance, or
weight, to some of the numbers. For that we used the weighted average, which is calculated as:</p>
<p><span class="math display">\[\begin{equation}
Weighted \ average= \frac{\sum_{i=1}^n (X_i * w)}{\sum_{i=1}^n  w} 
\end{equation}\]</span></p>
<p>where <span class="math inline">\(Xi\)</span> is a data value and w is the weight assigned to that data value.</p>
<p>Lets try an example.</p>
<p>Suppose your professor tells you that your grade will be based on a midterm and a final exam, each of which is based on 100 possible points. However, the final exam will be worth 60% of the grade and the midterm only 40%. How could you determine an average score that would reflect these different weights? The average you need is the weighted average.</p>
<p>If you scored 83 in your midterm and 95 in your final, what will be your final grade?.</p>
<p><span class="math display">\[\begin{equation}
Weighted \ average= \frac{(83*40)+(95*60)}{(40+60)} 
\end{equation}\]</span></p>
<p>So your final grade will be 90.2. Your average is high enough to earn an A, which I hope you all get in my class!. And if you have been paying attention, here are two tokens: jj</p>
</div>
<div id="the-median" class="section level3 unnumbered">
<h3>The median</h3>
<p>The median (also referred to as the 50th percentile) is the middle value in a sample of ordered values. Half the values are above the median and half are below the median.</p>
<p>To calculate the median, you start by sorting all values from lowest to highest, the <em>median</em> is the value in the middle.</p>
<p>When your set of numbers is odd, the median is the single value in the middle of the sorted list. Below is a vector of values indicating the price of different candy.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-157"></span>
<img src="images/Median%20odd%20Numbers.png" alt="Median calculation for odd number of values" width="100%" />
<p class="caption">
Figure 5.3: Median calculation for odd number of values
</p>
</div>
<p>When your set of numbers is even, you have a problem because there will be two numbers right in the middle of the sorted vector. In this case you report the arithmetic mean of the two values in the middle.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-158"></span>
<img src="images/Median%20Even%20Numbers.png" alt="Median calculation for even number of values" width="100%" />
<p class="caption">
Figure 5.4: Median calculation for even number of values
</p>
</div>
<p>y</p>
<p>In R, the median is calculated with the function median.</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="05-DescriptiveStatistics.html#cb148-1"></a>MEDIAN=<span class="kw">median</span> (y)  <span class="co">#here I calculate the mean, and assign it to a variable.</span></span>
<span id="cb148-2"><a href="05-DescriptiveStatistics.html#cb148-2"></a>MEDIAN           <span class="co">#to display the variable, simply type it, and click enter</span></span></code></pre></div>
<pre><code>## [1] -0.003001333</code></pre>
<p>p</p>
<p>Let’s plot the median with the mean value to the histogram we were doing before.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="05-DescriptiveStatistics.html#cb150-1"></a><span class="kw">hist</span>(y, <span class="dt">main =</span> <span class="ot">NULL</span>,<span class="dt">breaks =</span> <span class="dv">30</span>, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">110</span>),)</span>
<span id="cb150-2"><a href="05-DescriptiveStatistics.html#cb150-2"></a></span>
<span id="cb150-3"><a href="05-DescriptiveStatistics.html#cb150-3"></a><span class="co">#lets plot the mean</span></span>
<span id="cb150-4"><a href="05-DescriptiveStatistics.html#cb150-4"></a>MEAN=<span class="kw">mean</span>(y)</span>
<span id="cb150-5"><a href="05-DescriptiveStatistics.html#cb150-5"></a><span class="kw">abline</span>(<span class="dt">v=</span>MEAN, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="dv">5</span>) </span>
<span id="cb150-6"><a href="05-DescriptiveStatistics.html#cb150-6"></a><span class="kw">text</span>(<span class="st">&quot;Mean&quot;</span>,<span class="dt">x=</span>MEAN,<span class="dt">y=</span><span class="dv">110</span>, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">pos=</span><span class="dv">4</span>) <span class="co">#pos=4 means, to place the text to the right of the coordinates xy.</span></span>
<span id="cb150-7"><a href="05-DescriptiveStatistics.html#cb150-7"></a></span>
<span id="cb150-8"><a href="05-DescriptiveStatistics.html#cb150-8"></a><span class="co"># now the median</span></span>
<span id="cb150-9"><a href="05-DescriptiveStatistics.html#cb150-9"></a><span class="kw">abline</span>(<span class="dt">v=</span>MEDIAN, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>,<span class="dt">lwd=</span><span class="dv">3</span>, <span class="dt">lty=</span><span class="dv">2</span>) <span class="co">#I plot the median in blue to distinguish from the mean</span></span>
<span id="cb150-10"><a href="05-DescriptiveStatistics.html#cb150-10"></a><span class="kw">text</span>(<span class="st">&quot;Median&quot;</span>,<span class="dt">x=</span>MEDIAN,<span class="dt">y=</span><span class="dv">100</span>, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>, <span class="dt">pos=</span><span class="dv">2</span>) </span></code></pre></div>
<p><img src="GEOG380_files/figure-html/unnamed-chunk-160-1.png" width="672" /></p>
</div>
<div id="the-mode" class="section level3 unnumbered">
<h3>The mode</h3>
<p>The mode is simply the most common value in all of your data.</p>
<p>R does not have a standard in-built function to calculate mode. So we create a user function to calculate the mode of a dataset. This function takes a vector as input and gives the mode value as output.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="05-DescriptiveStatistics.html#cb151-1"></a>getmode &lt;-<span class="st"> </span><span class="cf">function</span>(v) {   <span class="co"># the function will take a vector of values</span></span>
<span id="cb151-2"><a href="05-DescriptiveStatistics.html#cb151-2"></a>   uniqv &lt;-<span class="st"> </span><span class="kw">unique</span>(v)      <span class="co">#select all the unique values in the vector </span></span>
<span id="cb151-3"><a href="05-DescriptiveStatistics.html#cb151-3"></a>   uniqv[<span class="kw">which.max</span>(<span class="kw">tabulate</span>(<span class="kw">match</span>(v, uniqv)))] <span class="co">#stimate the number of times each value appears and return the largest</span></span>
<span id="cb151-4"><a href="05-DescriptiveStatistics.html#cb151-4"></a>}</span></code></pre></div>
<p>Now let’s use our new function</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="05-DescriptiveStatistics.html#cb152-1"></a>MODE=<span class="kw">getmode</span>(y)  <span class="co">#here I calculate the mode, and assign it to a variable.</span></span>
<span id="cb152-2"><a href="05-DescriptiveStatistics.html#cb152-2"></a>MODE           <span class="co">#to display the variable, simply type it, and click enter</span></span></code></pre></div>
<pre><code>## [1] 0.01874617</code></pre>
<p>Unlike the mean and the median, the mode can also be used with character data (i.e., words). For instance, you want to know what is the most common name in the USA?. For that you can use the mode.</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="05-DescriptiveStatistics.html#cb154-1"></a><span class="co"># Create the vector with characters.</span></span>
<span id="cb154-2"><a href="05-DescriptiveStatistics.html#cb154-2"></a>NAMES &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Peter&quot;</span>, <span class="st">&quot;Carl&quot;</span>, <span class="st">&quot;Darrell&quot;</span>, <span class="st">&quot;John&quot;</span>, <span class="st">&quot;Peter&quot;</span>)</span>
<span id="cb154-3"><a href="05-DescriptiveStatistics.html#cb154-3"></a></span>
<span id="cb154-4"><a href="05-DescriptiveStatistics.html#cb154-4"></a><span class="kw">getmode</span>(NAMES)  <span class="co">#here I calculate the mode, and assign it to a variable.</span></span></code></pre></div>
<pre><code>## [1] &quot;Peter&quot;</code></pre>
<p>Let’s plot our mode in the histogram with the mean and the median we were working on before.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="05-DescriptiveStatistics.html#cb156-1"></a><span class="kw">hist</span>(y, <span class="dt">main =</span> <span class="ot">NULL</span>,<span class="dt">breaks =</span> <span class="dv">30</span>, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">110</span>),)</span>
<span id="cb156-2"><a href="05-DescriptiveStatistics.html#cb156-2"></a></span>
<span id="cb156-3"><a href="05-DescriptiveStatistics.html#cb156-3"></a><span class="co">#lets plot the mean</span></span>
<span id="cb156-4"><a href="05-DescriptiveStatistics.html#cb156-4"></a><span class="kw">abline</span>(<span class="dt">v=</span>MEAN, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="dv">6</span>) </span>
<span id="cb156-5"><a href="05-DescriptiveStatistics.html#cb156-5"></a><span class="kw">text</span>(<span class="st">&quot;Mean&quot;</span>,<span class="dt">x=</span>MEAN,<span class="dt">y=</span><span class="dv">110</span>, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">pos=</span><span class="dv">4</span>) </span>
<span id="cb156-6"><a href="05-DescriptiveStatistics.html#cb156-6"></a></span>
<span id="cb156-7"><a href="05-DescriptiveStatistics.html#cb156-7"></a><span class="co"># now the median</span></span>
<span id="cb156-8"><a href="05-DescriptiveStatistics.html#cb156-8"></a><span class="kw">abline</span>(<span class="dt">v=</span>MEDIAN, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>,<span class="dt">lwd=</span><span class="dv">4</span>, <span class="dt">lty=</span><span class="dv">2</span>) <span class="co">#I plot the median in blue to distinguish from the mean</span></span>
<span id="cb156-9"><a href="05-DescriptiveStatistics.html#cb156-9"></a><span class="kw">text</span>(<span class="st">&quot;Median&quot;</span>,<span class="dt">x=</span>MEDIAN,<span class="dt">y=</span><span class="dv">100</span>, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>, <span class="dt">pos=</span><span class="dv">2</span>) </span>
<span id="cb156-10"><a href="05-DescriptiveStatistics.html#cb156-10"></a></span>
<span id="cb156-11"><a href="05-DescriptiveStatistics.html#cb156-11"></a><span class="co">#now let&#39;s plot the mode</span></span>
<span id="cb156-12"><a href="05-DescriptiveStatistics.html#cb156-12"></a>MODE=<span class="kw">getmode</span>(y)</span>
<span id="cb156-13"><a href="05-DescriptiveStatistics.html#cb156-13"></a><span class="kw">abline</span>(<span class="dt">v=</span>MODE, <span class="dt">col=</span><span class="st">&quot;orange&quot;</span>,<span class="dt">lwd=</span><span class="dv">4</span>, <span class="dt">lty=</span><span class="dv">3</span>) <span class="co">#I plot the median in blue to distinguish from the mean</span></span>
<span id="cb156-14"><a href="05-DescriptiveStatistics.html#cb156-14"></a><span class="kw">text</span>(<span class="st">&quot;Mode&quot;</span>,<span class="dt">x=</span>MODE,<span class="dt">y=</span><span class="dv">90</span>, <span class="dt">col=</span><span class="st">&quot;orange&quot;</span>, <span class="dt">pos=</span><span class="dv">4</span>) </span></code></pre></div>
<p><img src="GEOG380_files/figure-html/unnamed-chunk-164-1.png" width="672" /></p>
<p>You should have noted that the mean, median and mode are almost the same in this case. That is because the data are normally distributed (follow a normal distribution).</p>
<p>Let’s see what happens when the data are skew.</p>
<p><img src="GEOG380_files/figure-html/unnamed-chunk-165-1.png" width="672" /></p>
<p>k</p>
<p>The reverse happens with a right or positive distribution:
<img src="GEOG380_files/figure-html/unnamed-chunk-166-1.png" width="672" /></p>
<p>If you see the two skewed distributions above, you will notice how the mean is pulled by the extreme values of the distribution. That is a critical consideration of the arithmetic mean, it is affected by extreme values or so-call <strong>outliers</strong>.</p>
<p>So a basic rule of thumb is to look at the mean and the median. If they’re the same you can just use the mean, that’s more easy for the average reader to understand. If they differ significantly report them both, or just report the median</p>
<p>With skew distributions is when it becomes important the distinction between the mean and the median. Lets check an example in which you can deceive a conclusion based on reporting only the mean.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-167"></span>
<img src="images/USA%20Household%20Income.png" alt="Income distribution in the USA" width="100%" />
<p class="caption">
Figure 5.5: Income distribution in the USA
</p>
</div>
<p>The figure above shows the household income of people in the USA. Clearly, the data follows a right distribution. In this distribution, the mean is larger than the median or the mode. So if you report the mean only, it may create an illusion that most people get paid well in the USA, when in reality most get paid much less.</p>
<p>In this case, the mean increases primarily as a result of the wealthy becoming wealthier. If we are concerned about how the average American is doing, median is actually a better measure to understand their status.</p>
<p>The figure below summarizes the central tendency metrics by the type of data distribution.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-168"></span>
<img src="images/Distribution%20Skews.png" alt="Central tendendy metrics in skew distributions" width="100%" />
<p class="caption">
Figure 5.6: Central tendendy metrics in skew distributions
</p>
</div>
<iframe src="https://www.impactsofclimatechange.info/H5P/wp-admin/admin-ajax.php?action=h5p_embed&amp;id=11" width="958" height="312" frameborder="0" allowfullscreen="allowfullscreen">
</iframe>
<script src="https://www.impactsofclimatechange.info/H5P/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>
</div>
</div>
<div id="dispersion" class="section level2 unnumbered">
<h2>Dispersion</h2>
<p>Dispersion refers to describing the spread of your data. And there are different metrics that may help you describe the variability in your data.</p>
<div id="the-minimum-and-the-maximum" class="section level3 unnumbered">
<h3>The minimum and the maximum</h3>
<p>The most basic metrics of the data dispersion are the minimum and the maximum. As their names indicate they are the lowest and the highest values in your data.</p>
<p>In R, the minimum and maximum are calculated with the function min and max, respectively.</p>
<p>Let’s plot them:</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="05-DescriptiveStatistics.html#cb157-1"></a><span class="kw">hist</span>(y, <span class="dt">main =</span> <span class="ot">NULL</span>,<span class="dt">breaks =</span> <span class="dv">30</span>, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">110</span>),)</span>
<span id="cb157-2"><a href="05-DescriptiveStatistics.html#cb157-2"></a></span>
<span id="cb157-3"><a href="05-DescriptiveStatistics.html#cb157-3"></a><span class="co">#lets plot the mean</span></span>
<span id="cb157-4"><a href="05-DescriptiveStatistics.html#cb157-4"></a><span class="kw">abline</span>(<span class="dt">v=</span>MEAN, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="dv">6</span>) </span>
<span id="cb157-5"><a href="05-DescriptiveStatistics.html#cb157-5"></a><span class="kw">text</span>(<span class="st">&quot;Mean&quot;</span>,<span class="dt">x=</span>MEAN,<span class="dt">y=</span><span class="dv">110</span>, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">pos=</span><span class="dv">4</span>) </span>
<span id="cb157-6"><a href="05-DescriptiveStatistics.html#cb157-6"></a></span>
<span id="cb157-7"><a href="05-DescriptiveStatistics.html#cb157-7"></a><span class="co"># now the median</span></span>
<span id="cb157-8"><a href="05-DescriptiveStatistics.html#cb157-8"></a><span class="kw">abline</span>(<span class="dt">v=</span>MEDIAN, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>,<span class="dt">lwd=</span><span class="dv">4</span>, <span class="dt">lty=</span><span class="dv">2</span>) <span class="co">#I plot the median in blue to distinguish from the mean</span></span>
<span id="cb157-9"><a href="05-DescriptiveStatistics.html#cb157-9"></a><span class="kw">text</span>(<span class="st">&quot;Median&quot;</span>,<span class="dt">x=</span>MEDIAN,<span class="dt">y=</span><span class="dv">100</span>, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>, <span class="dt">pos=</span><span class="dv">2</span>) </span>
<span id="cb157-10"><a href="05-DescriptiveStatistics.html#cb157-10"></a></span>
<span id="cb157-11"><a href="05-DescriptiveStatistics.html#cb157-11"></a><span class="co">#now let&#39;s plot the mode</span></span>
<span id="cb157-12"><a href="05-DescriptiveStatistics.html#cb157-12"></a><span class="kw">abline</span>(<span class="dt">v=</span>MODE, <span class="dt">col=</span><span class="st">&quot;orange&quot;</span>,<span class="dt">lwd=</span><span class="dv">4</span>, <span class="dt">lty=</span><span class="dv">3</span>) <span class="co">#I plot the median in blue to distinguish from the mean</span></span>
<span id="cb157-13"><a href="05-DescriptiveStatistics.html#cb157-13"></a><span class="kw">text</span>(<span class="st">&quot;Mode&quot;</span>,<span class="dt">x=</span>MODE,<span class="dt">y=</span><span class="dv">90</span>, <span class="dt">col=</span><span class="st">&quot;orange&quot;</span>, <span class="dt">pos=</span><span class="dv">4</span>) </span>
<span id="cb157-14"><a href="05-DescriptiveStatistics.html#cb157-14"></a></span>
<span id="cb157-15"><a href="05-DescriptiveStatistics.html#cb157-15"></a></span>
<span id="cb157-16"><a href="05-DescriptiveStatistics.html#cb157-16"></a><span class="co">#now let&#39;s plot the minimum</span></span>
<span id="cb157-17"><a href="05-DescriptiveStatistics.html#cb157-17"></a>MINIMUM=<span class="kw">min</span>(y)</span>
<span id="cb157-18"><a href="05-DescriptiveStatistics.html#cb157-18"></a><span class="kw">abline</span>(<span class="dt">v=</span>MINIMUM, <span class="dt">col=</span><span class="st">&quot;dark grey&quot;</span>,<span class="dt">lwd=</span><span class="dv">4</span>, <span class="dt">lty=</span><span class="dv">3</span>) <span class="co">#I plot the median in blue to distinguish from the mean</span></span>
<span id="cb157-19"><a href="05-DescriptiveStatistics.html#cb157-19"></a><span class="kw">text</span>(<span class="st">&quot;Minimum&quot;</span>,<span class="dt">x=</span>MINIMUM,<span class="dt">y=</span><span class="dv">90</span>, <span class="dt">col=</span><span class="st">&quot;dark grey&quot;</span>, <span class="dt">pos=</span><span class="dv">4</span>) </span>
<span id="cb157-20"><a href="05-DescriptiveStatistics.html#cb157-20"></a></span>
<span id="cb157-21"><a href="05-DescriptiveStatistics.html#cb157-21"></a><span class="co">#now let&#39;s plot the maximum</span></span>
<span id="cb157-22"><a href="05-DescriptiveStatistics.html#cb157-22"></a>MAXIMUM=<span class="kw">max</span>(y)</span>
<span id="cb157-23"><a href="05-DescriptiveStatistics.html#cb157-23"></a><span class="kw">abline</span>(<span class="dt">v=</span>MAXIMUM, <span class="dt">col=</span><span class="st">&quot;dark grey&quot;</span>,<span class="dt">lwd=</span><span class="dv">4</span>, <span class="dt">lty=</span><span class="dv">3</span>) <span class="co">#I plot the median in blue to distinguish from the mean</span></span>
<span id="cb157-24"><a href="05-DescriptiveStatistics.html#cb157-24"></a><span class="kw">text</span>(<span class="st">&quot;Maximum&quot;</span>,<span class="dt">x=</span>MAXIMUM,<span class="dt">y=</span><span class="dv">90</span>, <span class="dt">col=</span><span class="st">&quot;dark grey&quot;</span>, <span class="dt">pos=</span><span class="dv">2</span>) </span></code></pre></div>
<p><img src="GEOG380_files/figure-html/unnamed-chunk-169-1.png" width="672" /></p>
</div>
<div id="the-range" class="section level3 unnumbered">
<h3>The range</h3>
<p>Another simple metric to describe the dispersion in your data is called the <strong>range</strong>.u The range is the difference between the smallest and the largest number in your data. Of course, within the range everything is possible, so while descriptive and useful in many situations, it is not always the best indicator of inference.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-170"></span>
<img src="images/Inference.png" alt="The effect of the range" width="100%" />
<p class="caption">
Figure 5.7: The effect of the range
</p>
</div>
</div>
<div id="the-percentile" class="section level3 unnumbered">
<h3>The percentile</h3>
<p>A percentile indicates the percentage of values that are smaller than the given value.</p>
<p>For example, if you score 75 points on a test, and are ranked in the 85th percentile, it means that 85% of students that took that exam did worse than you. The way to report it is like this: “the 85th percentile was 75 points”.</p>
<p>How is the percentile calculated?. Simple,</p>
<ol style="list-style-type: decimal">
<li><p>Rank the values in your database from smallest to largest, we called this the sorted vector.</p></li>
<li><p>Multiply the number of values in your database by the given percentile you want to find as a fraction (If you want the 90th percentile, the fraction is 0.9), we call this resulting number the index or <span class="math inline">\(Xth\)</span> point</p></li>
<li><p>Now go back to your sorted vector, starting from the first number in that vector move to the right until the value located at the Xth point. The value located at the Xth point is your given percentile.</p></li>
</ol>
<p>Lets do an example,</p>
<p>Take my population of ten rabbits below, and say I want to know the 80th percentile height of my rabbits?</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-171"></span>
<img src="images/Percentile%201.png" alt="My rabbit population" width="100%" />
<p class="caption">
Figure 5.8: My rabbit population
</p>
</div>
<p>Because I am interested in height, I measure their heights. Say they were 37, 15, 35, 36, 5, 40, 41, 68, 45, and 56cm (I am making these numbers up, so do not overthink the size of my rabbits).</p>
<p>I sort my rabbits by height. Say their sorted heights are 5, 15, 35, 36, 37, 40, 41, 45, 56 and 68cm.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-172"></span>
<img src="images/Percentile.png" alt="My rabbits sorted by height" width="100%" />
<p class="caption">
Figure 5.9: My rabbits sorted by height
</p>
</div>
<p>Next, I multiply the percentile of interest (80th) as a fraction (i.e., 0.8) by the number of rabbits (10). So the 80th percentile height is the height of whatever rabbit is sitting in 8th position. In this case the number is 45. So the 80th percentile of my rabbit population is 45cm.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-173"></span>
<img src="images/Percentile%202.png" alt="The 80th percentile" width="100%" />
<p class="caption">
Figure 5.10: The 80th percentile
</p>
</div>
<p>In R, the percentile value in an vector of values is calculated with the function quantile. Basically, you need to enter the array of values, and the quantile you need (as a fraction).</p>
<p>Lets take the height of my rabbits above.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="05-DescriptiveStatistics.html#cb158-1"></a>MyRabbits=<span class="kw">c</span>(<span class="dv">37</span>, <span class="dv">15</span>, <span class="dv">35</span>, <span class="dv">36</span>, <span class="dv">5</span>, <span class="dv">40</span>, <span class="dv">41</span>, <span class="dv">68</span>, <span class="dv">45</span>, <span class="dv">56</span>) <span class="co">#vector of rabbit height, it does no</span></span>
<span id="cb158-2"><a href="05-DescriptiveStatistics.html#cb158-2"></a></span>
<span id="cb158-3"><a href="05-DescriptiveStatistics.html#cb158-3"></a><span class="kw">quantile</span>(MyRabbits, <span class="fl">.8</span>,<span class="dt">type =</span> <span class="dv">1</span>)                  <span class="co"># the type parameter allows you to use different ways to approximate the value. check ?quantile  for more details</span></span></code></pre></div>
<pre><code>## 80% 
##  45</code></pre>
</div>
<div id="the-quantile" class="section level3 unnumbered">
<h3>The quantile</h3>
<p>The quantiles are specific percentiles that divide the data in equal amounts. Quantiles can take different names. For instance, quartiles break the data in four groups, deciles in ten groups, and percentiles in 100 groups.</p>
<p>Lets take the quartile example. In this case, the data needs to be broken in four groups, so the breaking points will be 0.25, 0.5, and 0.75. Those break points will create four different categories in which I can group my data (0 to 0.25], (0.25 to 0.5], (0.5 to 0.75] and (0.75, 1]. They can also be called the 1st quartile, 2nd quartile, 3rd quartile and 4th quartile. You can see those indexes at times being called Q1, Q2, Q3, and Q4.</p>
<p>Lets display the quartiles for a normal distribution.</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="05-DescriptiveStatistics.html#cb160-1"></a><span class="kw">library</span> (RColorBrewer)</span>
<span id="cb160-2"><a href="05-DescriptiveStatistics.html#cb160-2"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb160-3"><a href="05-DescriptiveStatistics.html#cb160-3"></a><span class="kw">library</span>(scales)</span>
<span id="cb160-4"><a href="05-DescriptiveStatistics.html#cb160-4"></a><span class="kw">set.seed</span>(<span class="dv">3</span>)  </span>
<span id="cb160-5"><a href="05-DescriptiveStatistics.html#cb160-5"></a></span>
<span id="cb160-6"><a href="05-DescriptiveStatistics.html#cb160-6"></a></span>
<span id="cb160-7"><a href="05-DescriptiveStatistics.html#cb160-7"></a>dt &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">x=</span><span class="kw">rbeta</span>(<span class="dv">20000</span>,<span class="dv">100</span>,<span class="dv">100</span>)<span class="op">*</span><span class="dv">20000</span>)             <span class="co">#Lets create some dummy normal data</span></span>
<span id="cb160-8"><a href="05-DescriptiveStatistics.html#cb160-8"></a>dt<span class="op">$</span>x &lt;-<span class="st"> </span><span class="kw">rescale</span>(dt<span class="op">$</span>x,<span class="dt">to =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">100</span>), <span class="dt">from =</span> <span class="kw">range</span>(dt<span class="op">$</span>x))   <span class="co">#I rescale the data from 1 to 100 to better visualize the percentage results</span></span>
<span id="cb160-9"><a href="05-DescriptiveStatistics.html#cb160-9"></a></span>
<span id="cb160-10"><a href="05-DescriptiveStatistics.html#cb160-10"></a></span>
<span id="cb160-11"><a href="05-DescriptiveStatistics.html#cb160-11"></a>dt=dt <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(x)                  <span class="co">#Sort values from smallest to largest</span></span>
<span id="cb160-12"><a href="05-DescriptiveStatistics.html#cb160-12"></a>dt<span class="op">$</span>Position=<span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(dt)                <span class="co">#Rank each value from smallest to largest</span></span>
<span id="cb160-13"><a href="05-DescriptiveStatistics.html#cb160-13"></a>dt<span class="op">$</span>y=(dt<span class="op">$</span>Position<span class="op">/</span><span class="kw">nrow</span>(dt)) <span class="op">*</span><span class="dv">100</span>      <span class="co">#Assign the percentile position of each value</span></span>
<span id="cb160-14"><a href="05-DescriptiveStatistics.html#cb160-14"></a></span>
<span id="cb160-15"><a href="05-DescriptiveStatistics.html#cb160-15"></a><span class="co">#Create colors to make the plot look nicer</span></span>
<span id="cb160-16"><a href="05-DescriptiveStatistics.html#cb160-16"></a>ColSca &lt;-<span class="st"> </span><span class="kw">brewer.pal</span>(<span class="dv">9</span>, <span class="st">&#39;YlOrRd&#39;</span>)   <span class="co">#Create a vector of nice colors in the  YlOrRd color scale</span></span>
<span id="cb160-17"><a href="05-DescriptiveStatistics.html#cb160-17"></a>ColSca &lt;-<span class="st"> </span><span class="kw">colorRampPalette</span>(ColSca)  <span class="co">#create a color ramp for the colors above</span></span>
<span id="cb160-18"><a href="05-DescriptiveStatistics.html#cb160-18"></a>Colors=<span class="st"> </span><span class="kw">ColSca</span>(<span class="dv">110</span>) <span class="co">#create list of 100 colors in the ramp above</span></span>
<span id="cb160-19"><a href="05-DescriptiveStatistics.html#cb160-19"></a></span>
<span id="cb160-20"><a href="05-DescriptiveStatistics.html#cb160-20"></a><span class="co">#create histogram</span></span>
<span id="cb160-21"><a href="05-DescriptiveStatistics.html#cb160-21"></a><span class="kw">hist</span>(dt<span class="op">$</span>x, <span class="dt">col=</span>Colors,<span class="dt">main =</span> <span class="ot">NULL</span>,<span class="dt">breaks =</span> <span class="dv">100</span>, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">800</span>),<span class="dt">xlab=</span><span class="st">&quot;Percent&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Frequency&quot;</span>)  </span>
<span id="cb160-22"><a href="05-DescriptiveStatistics.html#cb160-22"></a></span>
<span id="cb160-23"><a href="05-DescriptiveStatistics.html#cb160-23"></a><span class="co">#calculate and add the quartiles and their names to the histogram.</span></span>
<span id="cb160-24"><a href="05-DescriptiveStatistics.html#cb160-24"></a>Prob=<span class="kw">c</span>(<span class="fl">0.25</span>,<span class="fl">0.5</span>,<span class="fl">0.75</span>,<span class="dv">1</span>)  <span class="co"># this is the list of values that define my four quartiles</span></span>
<span id="cb160-25"><a href="05-DescriptiveStatistics.html#cb160-25"></a>Quartiles=<span class="kw">quantile</span>(dt<span class="op">$</span>x,Prob ,<span class="dt">type =</span> <span class="dv">1</span>)  <span class="co">#calculate the quartiles of my data</span></span>
<span id="cb160-26"><a href="05-DescriptiveStatistics.html#cb160-26"></a></span>
<span id="cb160-27"><a href="05-DescriptiveStatistics.html#cb160-27"></a><span class="kw">abline</span>(<span class="dt">v=</span>Quartiles, <span class="dt">col=</span><span class="st">&quot;grey&quot;</span>,<span class="dt">lwd=</span><span class="dv">4</span>, <span class="dt">lty=</span><span class="dv">1</span>) <span class="co">#I plot the quartiles</span></span>
<span id="cb160-28"><a href="05-DescriptiveStatistics.html#cb160-28"></a></span>
<span id="cb160-29"><a href="05-DescriptiveStatistics.html#cb160-29"></a><span class="co"># now lets put names </span></span>
<span id="cb160-30"><a href="05-DescriptiveStatistics.html#cb160-30"></a>Names=<span class="kw">c</span>(<span class="st">&quot;Q1&quot;</span>, <span class="st">&quot;Q2&quot;</span>, <span class="st">&quot;Q3&quot;</span>, <span class="st">&quot;Q4&quot;</span>)   <span class="co">#vector of names for my quartiles</span></span>
<span id="cb160-31"><a href="05-DescriptiveStatistics.html#cb160-31"></a><span class="kw">text</span>(Names,<span class="dt">x=</span>Quartiles,<span class="dt">y=</span><span class="dv">800</span>, <span class="dt">col=</span><span class="st">&quot;black&quot;</span>, <span class="dt">pos=</span><span class="dv">2</span>) <span class="co">#place quartile names at y=800 and x= quartile values</span></span></code></pre></div>
<p><img src="GEOG380_files/figure-html/unnamed-chunk-175-1.png" width="672" /></p>
</div>
<div id="the-variance" class="section level3 unnumbered">
<h3>The variance</h3>
<p>The variance measures how far a set of numbers is spread out from their average value. Put in another way, the variance measures the average degree to which each number is different from the mean.</p>
<p>For a sample, the variance is calculated as:</p>
<p><span class="math display">\[\begin{equation}
Variance = s^2=\frac{\sum_{i=1}^n (X_i-\bar{X})^2}{n-1}
\end{equation}\]</span></p>
<p>For a population, the variance is calculated as:</p>
<p><span class="math display">\[\begin{equation}
Variance = σ^2=\frac{\sum_{i=1}^n (X_i-u)^2}{N}
\end{equation}\]</span></p>

<div class="rmdimportant">
<p>The parameter <span class="math inline">\((X_i-\bar{X})^2\)</span> is called <em>sum of squares</em>. Becuase each value is compared to the mean, if you do not square it, the result will be zero because the negative values will cancel the positive values. Squaring the difference between <span class="math inline">\((X_i-\bar{X})\)</span> will make the quantity nonnegative.</p>
</div>

<p>A few things you may have notice about these two equationss.</p>
<ol style="list-style-type: decimal">
<li><p>The equations are almost identical to the arithmetic mean. Indeed, they are. The variance can be thought of as the average of the differences from each value to the mean.</p></li>
<li><p>When calculating the variance of a population we use the capital letter N but lowercase letter n when it is a sample.</p></li>
<li><p>The variance of a population is defined with the letter <span class="math inline">\(σ^2\)</span>; for a sample it is the lowercase <span class="math inline">\(s^2\)</span>.</p></li>
<li><p>When calculating the variance of a sample, the denominator is n-1 but for a population is N. Since a random sample usually will not contain extreme data values (large or small), we divide by <span class="math inline">\(n-1\)</span> in the formula for s to make s a little larger than it would have been had we divided by n. It is called the unbiased estimate for s. If we have the population of all data values, then extreme data values are, of course, present, so we divide by N instead of <span class="math inline">\(n-1\)</span>.</p></li>
</ol>
<p>Let’s calculate the variance using a neat example, I took from <a href="https://www.mathsisfun.com/data/standard-deviation.html">Here</a>.</p>
<p>Here a group of children measured the height of their dogs in mm.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-177"></span>
<img src="images/Variance%201.gif" alt="Sample of dogs heights" width="100%" />
<p class="caption">
Figure 5.11: Sample of dogs heights
</p>
</div>
<p>The heights (at the shoulders) are: 600mm, 470mm, 170mm, 430mm and 300mm.</p>
<p>Next, you calculate the sample mean height, which is 394 mm (green line in figure below).</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="05-DescriptiveStatistics.html#cb161-1"></a>HeightOfDog=<span class="kw">c</span>(<span class="dv">600</span>, <span class="dv">470</span>, <span class="dv">170</span>, <span class="dv">430</span> , <span class="dv">300</span>)</span>
<span id="cb161-2"><a href="05-DescriptiveStatistics.html#cb161-2"></a></span>
<span id="cb161-3"><a href="05-DescriptiveStatistics.html#cb161-3"></a><span class="kw">mean</span>(HeightOfDog)</span></code></pre></div>
<pre><code>## [1] 394</code></pre>
<p>j</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-179"></span>
<img src="images/Variance%202.gif" alt="Sample of dogs heights" width="100%" />
<p class="caption">
Figure 5.12: Sample of dogs heights
</p>
</div>
<p>Next, for each dog, you calculate the difference of its height to the mean (Basically, the height between the red and the green line below),</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-180"></span>
<img src="images/Variance%202.gif" alt="Sample of dogs heights" width="100%" />
<p class="caption">
Figure 5.13: Sample of dogs heights
</p>
</div>
<p>Let’s isolate the individual differences:</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-181"></span>
<img src="images/Variance%203.gif" alt="Sample of dogs heights" width="100%" />
<p class="caption">
Figure 5.14: Sample of dogs heights
</p>
</div>
<p>Following the equation of the variance for a sample, you square each difference, then add them and divide them by the sample size minus one.</p>
<p><span class="math display">\[\begin{equation}
Variance = s^2=\frac{206^2 + 76^2 + (−224)^2 + 36^2 + (−94)^2}{5-1}
\end{equation}\]</span></p>
<p><span class="math display">\[\begin{equation}
Variance = s^2=27130mm^2
\end{equation}\]</span></p>
<p>In R, the variance is calculate with the function var,</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="05-DescriptiveStatistics.html#cb163-1"></a>HeightOfDog=<span class="kw">c</span>(<span class="dv">600</span>, <span class="dv">470</span>, <span class="dv">170</span>, <span class="dv">430</span> , <span class="dv">300</span>)</span>
<span id="cb163-2"><a href="05-DescriptiveStatistics.html#cb163-2"></a></span>
<span id="cb163-3"><a href="05-DescriptiveStatistics.html#cb163-3"></a><span class="kw">var</span>(HeightOfDog)</span></code></pre></div>
<pre><code>## [1] 27130</code></pre>
<p>Hmm, right?. The simplest variance to understand is when variance = 0, which means all values are the same. In reality, however, variance results are normally large numbers that are hard to interpret intuitively. But the variance allows you to calculate the standard deviation, which is actually much easy to comprehend.</p>
</div>
<div id="the-standard-deviation" class="section level3 unnumbered">
<h3>The standard deviation</h3>
<p>The standard deviation is calculated as the square root of the variance, and has the same units as the mean.</p>
<p><span class="math display">\[\begin{equation}
Standard \ deviation= S = \sqrt {s^2}
\end{equation}\]</span></p>
<p>In R, the standard deviation is calculated with the function sd,</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="05-DescriptiveStatistics.html#cb165-1"></a>HeightOfDog=<span class="kw">c</span>(<span class="dv">600</span>, <span class="dv">470</span>, <span class="dv">170</span>, <span class="dv">430</span> , <span class="dv">300</span>)</span>
<span id="cb165-2"><a href="05-DescriptiveStatistics.html#cb165-2"></a></span>
<span id="cb165-3"><a href="05-DescriptiveStatistics.html#cb165-3"></a><span class="kw">sd</span>(HeightOfDog)</span></code></pre></div>
<pre><code>## [1] 164.7119</code></pre>
<p>You can also try the square root of the variance,</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="05-DescriptiveStatistics.html#cb167-1"></a><span class="kw">sqrt</span>(<span class="kw">var</span>(HeightOfDog))</span></code></pre></div>
<pre><code>## [1] 164.7119</code></pre>
<p>Basically, SD= 164mm.</p>
<p>Now lets interpret that number….</p>
<p>In a normal distribution, 95% of the observations are within 2SD from the mean. So 95% of the dogs in the sample should between 394-(164mm x 2) and 394+(164mm x 2) or between 66mm and 722mm.</p>
<iframe src="https://www.impactsofclimatechange.info/H5P/wp-admin/admin-ajax.php?action=h5p_embed&amp;id=10" width="958" height="371" frameborder="0" allowfullscreen="allowfullscreen">
</iframe>
<script src="https://www.impactsofclimatechange.info/H5P/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>
<p>In the example with the dogs, we have the problem of low sample size. If you recall an earlier chapter, the problem with low samples is that the variability increases as the sample size decreases and that is reflected in the standard deviation (SD).</p>
<p>Lets try the standard deviation in a large sample size.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="05-DescriptiveStatistics.html#cb169-1"></a>y &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">1000</span>) <span class="co"># the function rnorm allows you to create a random set of numbers from a normal distribution</span></span>
<span id="cb169-2"><a href="05-DescriptiveStatistics.html#cb169-2"></a></span>
<span id="cb169-3"><a href="05-DescriptiveStatistics.html#cb169-3"></a><span class="co">#lets now plot that data using the hist function, you already know how to use:</span></span>
<span id="cb169-4"><a href="05-DescriptiveStatistics.html#cb169-4"></a><span class="kw">hist</span>(y, <span class="dt">main =</span> <span class="ot">NULL</span>,<span class="dt">breaks =</span> <span class="dv">30</span>,<span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">120</span>))</span>
<span id="cb169-5"><a href="05-DescriptiveStatistics.html#cb169-5"></a></span>
<span id="cb169-6"><a href="05-DescriptiveStatistics.html#cb169-6"></a>SD=<span class="kw">sd</span>(y)</span>
<span id="cb169-7"><a href="05-DescriptiveStatistics.html#cb169-7"></a>Mean=<span class="kw">mean</span>(y)</span>
<span id="cb169-8"><a href="05-DescriptiveStatistics.html#cb169-8"></a></span>
<span id="cb169-9"><a href="05-DescriptiveStatistics.html#cb169-9"></a><span class="co">#plot the mean</span></span>
<span id="cb169-10"><a href="05-DescriptiveStatistics.html#cb169-10"></a><span class="kw">abline</span>(<span class="dt">v=</span>(Mean), <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>,<span class="dt">lwd=</span><span class="dv">4</span>)</span>
<span id="cb169-11"><a href="05-DescriptiveStatistics.html#cb169-11"></a><span class="kw">text</span>(<span class="st">&quot;Mean&quot;</span>,<span class="dt">x=</span>Mean,<span class="dt">y=</span><span class="dv">100</span>, <span class="dt">col=</span><span class="st">&quot;Blue&quot;</span>, <span class="dt">pos=</span><span class="dv">4</span>) </span>
<span id="cb169-12"><a href="05-DescriptiveStatistics.html#cb169-12"></a></span>
<span id="cb169-13"><a href="05-DescriptiveStatistics.html#cb169-13"></a><span class="co">#add two standard deviations </span></span>
<span id="cb169-14"><a href="05-DescriptiveStatistics.html#cb169-14"></a><span class="kw">abline</span>(<span class="dt">v=</span>(Mean<span class="op">+</span>(SD<span class="op">*</span><span class="dv">2</span>)), <span class="dt">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb169-15"><a href="05-DescriptiveStatistics.html#cb169-15"></a><span class="kw">text</span>(<span class="st">&quot;+2 SDs&quot;</span>,<span class="dt">x=</span>(Mean<span class="op">+</span>(SD<span class="op">*</span><span class="dv">2</span>)),<span class="dt">y=</span><span class="dv">100</span>, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>, <span class="dt">pos=</span><span class="dv">4</span>) </span>
<span id="cb169-16"><a href="05-DescriptiveStatistics.html#cb169-16"></a></span>
<span id="cb169-17"><a href="05-DescriptiveStatistics.html#cb169-17"></a></span>
<span id="cb169-18"><a href="05-DescriptiveStatistics.html#cb169-18"></a><span class="co">#minus two standard deviations </span></span>
<span id="cb169-19"><a href="05-DescriptiveStatistics.html#cb169-19"></a><span class="kw">abline</span>(<span class="dt">v=</span>(Mean<span class="op">-</span>(SD<span class="op">*</span><span class="dv">2</span>)), <span class="dt">col=</span><span class="st">&quot;red&quot;</span>) </span>
<span id="cb169-20"><a href="05-DescriptiveStatistics.html#cb169-20"></a><span class="kw">text</span>(<span class="st">&quot;-2 SDs&quot;</span>,<span class="dt">x=</span>(Mean<span class="op">-</span>(SD<span class="op">*</span><span class="dv">2</span>)),<span class="dt">y=</span><span class="dv">100</span>, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>, <span class="dt">pos=</span><span class="dv">4</span>) </span></code></pre></div>
<p><img src="GEOG380_files/figure-html/unnamed-chunk-185-1.png" width="672" /></p>
<p>In the figure above, ~95% of the data should be between those two red lines.</p>
</div>
<div id="the-coefience-of-variance" class="section level3 unnumbered">
<h3>The coefience of variance</h3>
<p>The coefficient of variation (CV) is another metric of dispersion. It is the ratio of the standard deviation to the mean. It is commonly given as a percentage. Basically,</p>
<p><span class="math display">\[\begin{equation}
CV = \frac{Standard \ deviation}{\bar{X}} *100
\end{equation}\]</span></p>
<p>Higher values indicate that the standard deviation is relatively large compared to the mean.</p>
<p>Lets try an example, a pizza restaurant measures its delivery time in minutes. The mean delivery time is 20 minutes and the standard deviation is 5 minutes.</p>
<p>Thus, the coefficient of variation is 25% (some people may give it as a fraction, 0.25). This value tells you the relative size of the standard deviation compared to the mean. In this example, the standard deviation is 25% the size of the mean.</p>
<p>If the value equals one or 100%, the standard deviation equals the mean. Values less than one indicate that the standard deviation is smaller than the mean (typical), while values greater than one occur when the S.D. is greater than the mean.</p>
</div>
</div>
<div id="exercises" class="section level2 unnumbered">
<h2>Exercises</h2>
<p>Some of these questions may take a while to load depending on your internet connection.</p>
Assign the names to each distribution.
<iframe src="https://www.impactsofclimatechange.info/H5P/wp-admin/admin-ajax.php?action=h5p_embed&id=5" width="958" height="928" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
<script src="https://www.impactsofclimatechange.info/H5P/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>
<p><span style="color: white;">o</span></p>
<p>Take the following numbers (8 2 7 2 6), using the R console below estimate the mean, median, and mode, the standard deviation and 80th percentile.</p>
<iframe width="100%" height="300" src="https://rdrr.io/snippets/embed/" frameborder="0">
</iframe>
Now lets check some equations:
<iframe src="https://www.impactsofclimatechange.info/H5P/wp-admin/admin-ajax.php?action=h5p_embed&id=12" width="959" height="647" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
<script src="https://www.impactsofclimatechange.info/H5P/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js" charset="UTF-8"></script>
</div>
<div id="homework-2" class="section level2 unnumbered">
<h2>Homework</h2>
<p>In Tinn-R, write down a code that:</p>
<ol style="list-style-type: decimal">
<li><p>Creates a sample of 1000 points from a normal distribution, and place them in a data.frame, with one column named X.</p></li>
<li><p>Estimate the mean, median and mode of variable X; have these individual values stored in their own variable names.</p></li>
<li><p>Estimate the standard deviation and place it in its own variable name.</p></li>
<li><p>Make a histogram of the data you created in numeral one. Adjust parameters of the figure to the guidelines for good figures.</p></li>
<li><p>Place the mean, median, mode and 2SDs from the mean as vertical lines. Make the color lines distinctive.</p></li>
<li><p>Name the vertical lines above. Work with the XY position of the ‘text’ so the labels look nice.</p></li>
<li><p>Save the code and email it as a homework.</p></li>
</ol>

</div>
</div>
<div id="disqus_thread"></div>
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://basic-stats-with-r.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
            </section>

          </div>
        </div>
      </div>
<a href="04-RBasics-Plots.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/Camilo-Mora/GEOG380/blob/main/05-DescriptiveStatistics.Rmd",
"text": null
},
"download": ["GEOG380.pdf", "GEOG380.epub"],
"toc": {
"collapse": "subsection"
},
"highlight": "pigments"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
